version: '3'

services:
  lexicalanalyzer:
    build: ./lexicalanalyzer
    ports:
      - "8081:8080"
    networks:
      - primary
    env_file: ./lexicalanalyzer.env

  db:
    image: mariadb:10.5.8
    env_file:
      - ./db.env
    ports:
      - "3306:3306"
    volumes:
      - /reflectiment/mariadb:/var/lib/mysql
    networks:
      - primary
    command: --lower_case_table_names=1

# Stuff below here is from another project's Dockerfile - just leaving here for easy reference for now
#  sql:
#    image: mysql:8.0
#    ports:
#      - "3306:3306"
#    volumes:
#      - /courier/rebuild/mysql:/var/lib/mysql
#    networks:
#      - primary
#    env_file: ./sql.env
#    command: --lower_case_table_names=1
#
#  mongo:
#    image: mongo:4.4-bionic
#    ports:
#      - "27017:27017"
#    volumes:
#      - /var/lib/mongodb:/data/db
#    networks:
#      - primary
#
#  campus:
#    build: ./campus/campus
#    ports:
#      - "8081:8080"
#    depends_on:
#      - sql
#    networks:
#      - primary
#    env_file: ./campus.env
#
#  chatterbox:
#    build: ./chatterbox/chatterbox
#    ports:
#      - "8082:8080"
#    depends_on:
#      - sql
#    networks:
#      - primary
#    env_file: ./chatterbox.env
#
#  postie:
#    build: ./postie
#    ports:
#      - "8083:8080"
#    depends_on:
#      - mongo
#    networks:
#      - primary
#    env_file: ./postie.env

networks:
  primary:
    driver: bridge